# Site settings
title: Test domain
email: your-email@domain.com
baseurl: "/main" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: One sentence introducing yourself or what you do

# Social icons
facebook: username
linkedin: username
github: username
deviantart: username
codepen: username

footer: © Mohit

# Build settings
markdown: kramdown
